[package]
name = "sg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.20"
colored = "2.1.0"
ctrlc = "3.4.5"
dirs = "5.0.1"
flexi_logger = "0.29.4"
log = "0.4.22"
rayon = "1.10.0"
regex = "1.11.0"
walkdir = "2.5.0"
